version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  note-service:
    container_name: note-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

